[build]
target = "i686-king.json"

[unstable]
# Use underscores here to satisfy the package ID requirement
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.'targetjson(i686-king.json)']
rustflags = [
    "-C", "code-model=small",
    "-C", "relocation-model=static",
]